### PR TITLE
added support for multiple values per declaration closes #2

### LINKED ISSUE #2: [bug]: Fails when a declaration contains multiple rem values
Example:

`padding: 1rem 2rem 3rem 4rem;`
would be translated to
`padding:16px;`

### PR DESCRIPTION
**Pull request by ppowalowski**
Solves #2 .

### CODE REVIEW

**Comment by nfroidure** [comment]
Thanks for your PR. Would you be interested in an ownership transfer? I don't maintain nor use this repo anymore.

**Comment by ppowalowski** [comment]
Hi, 

Thanks for pulling in my PR.
I am planning on using this actively for at least several months to come. I wrote a gulp wrapper with which I'll be building some bigger stylesheets in production. I have this code up and running so I am into taking care of it.

Are you familiar how the process of handing over repos works?

Thanks

**Comment by nfroidure** [comment]
It's simple, you just have to remove your fork and i'll be able to transfer the repo's ownership.

**Comment by ppowalowski** [comment]
Ready to go.

**Comment by nfroidure** [comment]
Done. Have a nice day.

**Comment by nfroidure** [comment]
FYI i also added you as a maintainer of the npm packege so that you can publish your changes.

**Comment by ppowalowski** [comment]
Great. Thanks

**Pull request merged**
